export const GET_EVENTS_REQUESTED = 'GET_EVENTS_REQUESTED';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED';

export const ADD_EVENT_REQUESTED = 'ADD_EVENT_REQUESTED';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILED = 'ADD_EVENT_FAILED';

export const GET_WEATHERS_REQUESTED = 'GET_WEATHERS_REQUESTED';
export const GET_WEATHERS_SUCCESS = 'GET_WEATHERS_SUCCESS';
export const GET_WEATHERS_FAILED = 'GET_WEATHERS_FAILED';